apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-nodejs
  template:
    metadata:
      labels:
        app: webapp-nodejs
    spec:
      containers:
      - name: webapp-nodejs
        image: 211125606237.dkr.ecr.eu-north-1.amazonaws.com/webapp-nodejs:latest
        ports:
          - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp-nodejs
